server:
  port: 0  # This tells Spring Boot to use a random available port

spring:
  application:
    name: Authentication  # This should match the Consul path

  #-----------------------------------------------#
  # POSTGRES DATABASE CONFIGURATION               #
  #-----------------------------------------------#
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_authentication
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

  #-----------------------------------------------#
  # RABBIT MQ CONFIGURATION                       #
  #-----------------------------------------------#
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password



  #-----------------------------------------------#
  # CONSUL CONFIGURATION                          #
  #-----------------------------------------------#
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: yaml
        prefixes: config
        data-key: configuration_file
        default-context: ${spring.application.name}
        enabled: false
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}  # Unique instance ID
        service-name: Authentication
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
  config:
    import: "optional:consul:"

management:
  endpoints:
    web:
      exposure:
        include: health, info