##############################################
# CONFIG FOR DEPLOY                          #
##############################################


server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: WebscraperService

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}  # Unique instance ID
        service-name: WebscraperService
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 2s
  config:
    import: "optional:consul:"

management:
  endpoints:
    web:
      exposure:
        include: health, info  # Expose health and info endpoints

---
spring:
  config:
    activate:
      on-profile: production