##############################################
# CONFIG FOR LOCAL                           #
##############################################

google:
  cx: 178c48d27a6b145d9
  api_key: AIzaSyDjUBYwYTQ1vs143c3qO-Eiep8UVDt7dow

server:
  port: 0
  address: 0.0.0.0  # Bind to all interfaces so it's accessible from the Docker container

spring:
  application:
    name: WebscraperService

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: yaml
        prefixes: config
        data-key: configuration_file
        default-context: ${spring.application.name}
        enabled: false
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${random.value}  # Unique but consistent instance ID per deployment
        service-name: ${spring.application.name}
        prefer-ip-address: true  # Ensure IP is used for service registration
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-critical-timeout: 30s  # Allows for some health check failures before removing the service
        register: true  # Register this service with Consul
        register-health-check: true  # Automatically add the health check

management:
  endpoints:
    web:
      exposure:
        include: health, info  # Expose health and info endpoints