######################################################################
#  DOCKER-COMPOSEE
#
#  Purpose:
#    For building images locally and running all containers.
#
######################################################################

services:

  ##############################################
  # CONSUL IMPORTER & CONSUL                   #
  ##############################################
  consul-importer:
    container_name: ms_consul_importer
    build:
      context: "./docker/consul" #Find the config file in there and use base64 encoder for the values
      dockerfile: Dockerfile
    depends_on:
      - consul
    networks:
      - microservices-network
  consul:
    image: hashicorp/consul
    container_name: ms_dev_consul
    ports:
      - '8500:8500' # Consul UI and agent port
      - '8600:8600/udp'
    networks:
      - microservices-network
    command: 'agent -dev -node=pdc_microservices -client=0.0.0.0 -log-level=DEBUG'
    environment:
      - HOST_IP=host.docker.internal

  ##############################################
  # OTHER FACILITATING SERVICES                #
  ##############################################
  postgres:
    image: postgres:15-alpine
    container_name: ms_dev_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./docker/db/init_databases.sql:/docker-entrypoint-initdb.d/init-databases.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ms_dev_rabbitmq
    networks:
      - microservices-network
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password


  ##############################################
  # ACTUAL MICROSERVICES                       #
  ##############################################
  ms-company-manager:
    build:
      context: ./companyManager
      dockerfile: Dockerfile
    image: williamcaamot/ms_companymanager:latest
    #container_name: ms_companymanager # Breaks if used along with deploy & replicas
    ports:
      - "0:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq
      - consul
    deploy:
      replicas: 2
  ms-authentication:
    build:
      context: ./Authentication
      dockerfile: Dockerfile
    image: williamcaamot/ms_authentication:latest
    ports:
      - "0:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq
      - consul
    deploy:
      replicas: 2
  ms-gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    image: williamcaamot/ms_gateway:latest
    #container_name: ms_companymanager # Breaks if used along with deploy & replicas
    ports:
      - "0:8000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq
      - consul
    deploy:
      replicas: 1
  ms-webscraperservice:
    build:
      context: ./webscraperServiceV2
      dockerfile: Dockerfile
    image: williamcaamot/ms_webscraperservice:latest
    ports:
      - "0:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq
      - consul
    deploy:
      replicas: 2
  ms-aiservice:
    build:
      context: ./AIService
      dockerfile: Dockerfile
    image: williamcaamot/ms_aiservice:latest
    ports:
      - "0:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network
    depends_on:
      - postgres
      - rabbitmq
      - consul
    deploy:
      replicas: 2

  ms-frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: williamcaamot/ms_frontend:latest
    ports:
      - "5173:5173"  # Expose Vite port on host machine
    #environment:
    #  - NODE_ENV=production
    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge