version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ms_dev_postgres
    environment:
      POSTGRES_DB: proptools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - microservices-network
  consul:
    image: hashicorp/consul
    container_name: ms_dev_consul
    ports:
      - "8500:8500"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge