######################################################################
#  DOCKER-COMPOSEE
#
#  Purpose:
#    For building images locally and running all containers.
#
######################################################################

services:

  ##############################################
  # CONSUL IMPORTER & CONSUL                   #
  ##############################################
  consul-importer:
    container_name: mc_consul_importer
    build:
      context: "./docker/consul" #Find the config file in there and use base64 encoder for the values
      dockerfile: Dockerfile
    depends_on:
      - consul
    networks:
      - ms_network
  consul:
    image: hashicorp/consul
    container_name: ms_consul
    ports:
      - '8500:8500'
    command: 'agent -dev -node=wca_microservices -client=0.0.0.0 -log-level=INFO'
    networks:
      - ms_network

  ##############################################
  # OTHER FACILITATING SERVICES                #
  ##############################################
  microservicePostgres:
    image: postgres:15-alpine
    container_name: ms_postgres
    environment:
      POSTGRES_DB: proptools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - ms_network


  ##############################################
  # ACTUAL MICROSERVICES                       #
  ##############################################
  property-manager:
    build:
      context: ./companyManager
      dockerfile: Dockerfile
    image: galovex/company-manager:latest
    container_name: ms_companymanager
    ports:
      - "8081:8081"  # Exposing the service on port 8081 externally
    networks:
      - ms_network
    depends_on:
      - microservicePostgres
      - consul
      - consul-importer


networks:
  ms_network:
    driver: bridge