services:
  postgres:
    image: postgres:15-alpine
    container_name: ms_dev_postgres
    environment:
      POSTGRES_DB: proptools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - microservices-network
  consul:
    image: hashicorp/consul
    container_name: ms_dev_consul
    ports:
      - "8500:8500"
    networks:
      - microservices-network
  frontend:
    image: node:20.1.0-alpine  # Node.js version suitable for your frontend
    container_name: ms_dev_frontend
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend  # Mount your frontend directory
    command: sh -c "npm install && npm run dev -- --host"  # Expose Vite server
    ports:
      - "5173:5173"  # Expose Vite port on host machine
    environment:
      - NODE_ENV=development
    networks:
      - microservices-network
  rabbitMq:
    image: rabbitmq:3-management
    container_name: ms_dev_rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: password
networks:
  microservices-network:
    driver: bridge