server:
  port: 0  # This tells Spring Boot to use a random available port

spring:
  application:
    name: "CompanyManager"
  datasource:
    url: jdbc:postgresql://localhost:5432/proptools
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}  # Unique instance ID
        service-name: CompanyManager
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s

management:
  endpoints:
    web:
      exposure:
        include: health, info

# Production profile:
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://microservicePostgres:5432/proptools
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0  # Use random port in production as well