##############################################
# CONFIG FOR DEPLOY                          #
##############################################

server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: 'CompanyManager'
  datasource:
    url: jdbc:postgresql://postgres:5432/ms_companymanager
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  #-----------------------------------------------#
  # RABBIT MQ CONFIGURATION                       #
  #-----------------------------------------------#
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password

  #-----------------------------------------------#
  # CONSUL CONFIGURATION                          #
  #-----------------------------------------------#
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}  # Unique instance ID
        service-name: CompanyManager
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 2s
  config:
    import: "optional:consul:"


management:
  endpoints:
    web:
      exposure:
        include: health, info
      #endpoint:
      #health:
      #show-details: always

# Production profile:
---
spring:
  config:
    activate:
      on-profile: production