##############################################
# CONFIG FOR LOCAL                           #
##############################################

server:
  port: 0  # This tells Spring Boot to use a random available port
  address: 0.0.0.0

spring:
  application:
    name: "CompanyManager"
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_companymanager
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
  #-----------------------------------------------#
  # RABBIT MQ CONFIGURATION                       #
  #-----------------------------------------------#
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password


  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: yaml
        prefixes: config
        data-key: configuration_file
        default-context: ${spring.application.name}
        enabled: false
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}  # Unique instance ID
        service-name: CompanyManager
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 2s


management:
  endpoints:
    web:
      exposure:
        include: health, info