server:
  port: 8000

spring:
  application:
    name: "Gateway"
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        format: yaml
        prefixes: config
        data-key: configuration_file
        default-context: ${spring.application.name}
        enabled: false
      discovery:
        enabled: true
        instance-id: ${spring.application.name}-${server.port}
        service-name: Gateway
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:80"
              - "http://ms-frontend:80"
              - "http://ms-frontend:5173"
            allowed-headers:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST
  config:
    import: "optional:consul:"
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.ecwid.consul: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, service