##############################################
# config for DEV      AI SERVICE             #
##############################################

server:
  port: 0  # This tells Spring Boot to use a random available port
  address: 0.0.0.0


spring:
  application:
    name: AIService  # This should match the Consul path
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_aiservice
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

  #-----------------------------------------------#
  # RABBIT MQ CONFIGURATION                       #
  #-----------------------------------------------#
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  #-----------------------------------------------#
  # CONSUL CONFIGURATION                          #
  #-----------------------------------------------#
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${random.value}  # Unique instance ID
        service-name: AIService
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 2s
  config:
    import: "optional:consul:"  # This tells Spring Boot to fetch configuration from Consul



management:
  endpoints:
    web:
      exposure:
        include: health, info