services:
  consul-importer:
    build:
      context: "./"
      dockerfile: Dockerfile
    depends_on:
      - consul-dev
    networks:
      - microservices
  consul-dev:
    image: hashicorp/consul
    container_name: consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
    command: 'agent -dev -node=learnmicro -client=0.0.0.0 -log-level=INFO'
    networks:
      - microservices

networks:
  microservices:
    driver: bridge