name: Build Docker Images
on:
  push:
    branches:
      - main
jobs:
  build:
    name: push docker images to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build companyManager/ -f companyManager/Dockerfile -t williamcaamot/ms_companymanager:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUBUSERNAME}}/ms_companymanager:latest