name: Build Docker Images
on:
  push:
    branches:
      - main
jobs:
  buildCompanyManager:
    name: Companymanager build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build companyManager/ -f companyManager/Dockerfile -t williamcaamot/ms_companymanager:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUBUSERNAME}}/ms_companymanager:latest
  buildAuthentication:
    name: Authentication build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build Authentication/ -f Authentication/Dockerfile -t williamcaamot/ms_authentication:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUBUSERNAME}}/ms_authentication:latest
  buildGateway:
    name: Gateway build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build Authentication/ -f Gateway/Dockerfile -t williamcaamot/ms_gateway:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUBUSERNAME}}/ms_gateway:latest
  buildWebscraperService:
    name: WebscraperService build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKERHUBUSERNAME}}
          password: ${{secrets.DOCKERHUBPASSWORD}}
        run: |
          docker login -u $username -p $password
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build Authentication/ -f webscraperServiceV2/Dockerfile -t williamcaamot/ms_webscraperservice:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push ${{secrets.DOCKERHUBUSERNAME}}/ms_webscraperservice:latest